### ISSUE TITLE
不知道是不是我读书少

### ISSUE THREAD

**Issue by woshihoujinxin** [zzhoujay/Gank4Android#1]
建议将代码风格改的更加groovy一些，如省略return， 省略类型声明，不然看着总以为只是把java文件的扩展名改为groovy，然后就声称这是用groovy开发的，不喜请忽略

**Comment by zzhoujay** [comment]
由于写这个项目的目的旨在学习groovy，在学习的前期有些地方还不太适应所以写出了和Java类似的代码。由于groovy性能的原因我不得不使用groovy的静态编译和类型检查，所以在一些地方我还是声明了变量类型，如果只是单纯的写groovy脚本当然是可以“纯groovy”的方式，但经过我的测试这样性能极低，所以有些地方我不得不做取舍，望见谅
