### ISSUE TITLE
红米2  Android5.1 直接闪退

### ISSUE THREAD

**Issue by gzfgeh** [zzhoujay/Gank4Android#3]

**Comment by zzhoujay** [comment]
能把错误的日志贴一下么，方便找到问题

**Comment by gzfgeh** [comment]
Error:Execution failed for task ':app:compileDebugGroovyWithGroovyc'.

> No such property: bootClasspath for class: com.android.builder.core.AndroidBuilder

**Comment by zzhoujay** [comment]
好的，我会尽力解决的

**Comment by zzhoujay** [comment]
推荐使用[DailyGank](https://github.com/zzhoujay/DailyGank)来代替本项目
